### ISSUE TITLE
idea：把数据分离出来 white_domains.yml

### ISSUE THREAD

**Issue by ifyour** [ifyour/ipac#1]
- 易读、好维护
- 自动生成更新日期
- push 后触发 Zeit Now 输出 pac.js

```yml
com:
  baidu: 1
  qq: 1
  jd: 1
  yuque: 1
im:
  juejin: 1
```

## Library
- [Convert YAML to JSON online](https://www.json2yaml.com/convert-yaml-to-json)
- ? ymlTojson for nodejs
